### ISSUE TITLE
activate user by email?

### ISSUE THREAD

**Issue by Manuel-Steinberg** [kreativ-anders/kirby-userkit#4]
|Pro|Contra|
|---|---|
|validates users email|personal data|
||requires mail server|
||privacy concerns|
||new potential errors|

More pro-arguments?

**Comment by arnoson** [comment]
Another pro might be spam protection, without a email validation a person could create lots of users. I'm not sure if this will ever happen with a smaller website, but it still feels better to have an email activation. 

As the email activation is optional (I could still use a normal user registration as it already exists in the kirby-userkit) it will be only used by people who are wanting this feature and therefore will provide an email server.

I don't see a big privacy concern, as you don't have to save the email address. It is just used to send the activation email and from there on only the activation token matters. Are there other things to take care of?

Personally I would love to see this feature :)

**Comment by Manuel-Steinberg** [comment]
Thanks for sharing your thoughts 👍🏻 Maybe, I will have a technical look on this later the week.

**Comment by arnoson** [comment]
Great! If you are planing to add the feature I would be happy to contribute. Still not sure whats the best way to solve it. starckio's [Userkit ](https://github.com/starckio/Userskit) seems to change the password when the user clicks the activation link, but I haven't completely understood whats going on. I have been thinking about either having a flag on the user like `activated` and checking it on each login, oder maybe create a new user role like `unactivated` und use this role on user creation und when activating change the user role.

**Comment by Manuel-Steinberg** [comment]
@arnoson feel free to check out the new [branch `email_activation`](https://github.com/kreativ-anders/kirby-userkit/tree/email_activation) 🎉

- After registration the user will be logged in automatically.

> I think this might be the reason why users are logged out in starckio´s Userkit and and the token is set as new password!? 🤔

- Via the "flag" (`emailActivation`) it is possible to check the **status**. 

| Status | Description | 
|---|---|
| false / emtpy (bool) | Email activation is disabled and therefore not present in user.txt |
| token (alphanum) | Email activation is enabled and the email is not activated |
| true / 1 | Email activation is enabled and the email has been activated | 

- Customizable email templates (`site\templates\emails\account-activation.*.php`) 
- The activated link equals the pattern `user/activate/*EMAIL*/*TOKEN*`

> Maybe masking (base64) / encrypting the email to "hide" the email in plain text? 🤔

- Removed `lastLogin` hook since multiple hooks can make a lot of trouble.

**Comment by arnoson** [comment]
Wow that was quick! Looks great (:
As for your question wether to mask the email or not: maybe the we don't even need the email in the link and just look up the token? This is what starckio did. For short tokens there could be a collision, but I guess for 12 characters this shold be very unlikely.

**Comment by Manuel-Steinberg** [comment]
Fair points! Since the process is **very temporarily** at all, I can live with that unclear unsexy workaround regarding the flag 😁  

```php
if(filter_var($user()->emailActivation(), FILTER_VALIDATE_BOOLEAN) != true)
```
----
```php
$user = $kirby->users()->findBy('token', $token)
```
^^ I saw that approach as well, but somehow I am not convinced... 🤔

**Comment by arnoson** [comment]
What does the check with `filter_var` do, couldn't I just write `if ($user->emailActivation() == true)`?
I still find this flag a bit unclear and I makes it easier to make an error if you forget to check for `true`, which could result in showing content to users that shouldn't see it.

What are your concerns with the find by token approach?

**Comment by Manuel-Steinberg** [comment]
```php
var_dump($user()->emailActivation()); // --> object(Kirby\Cms\Field)#294 (1) { ["emailactivation"]=> string(0) "" } 
var_dump(r($user()->emailActivation(), true, false)); // --> bool(true) 😵
var_dump(r($user()->emailActivation() != true, true, false)); // --> bool(false)
```

Totally confusing ... Anyhow, I switched to 2 independent flags now and use `findBy()`-solution. Even it´s a temporarily process code should be easy and understandable! 

> Regarding your question: IDK, gut feeling.

@arnoson Do you mind to do some additional testing?

Also an optional todo would be to provide a migration script...

**Comment by arnoson** [comment]
I will do some testing next week!

**Comment by arnoson** [comment]
Sorry it took a bit longer! I tested the new userkit right now and everything worked for me

**Comment by Manuel-Steinberg** [comment]
Just did the merge. 
Thanks for your help @arnoson
