### ISSUE TITLE
Future Version Brainstorming

### ISSUE THREAD

**Issue by Manuel-Steinberg** [kreativ-anders/kirby-userkit#5]
### Only frontend registration!

> Kirby CMS provides a powerful User Management for the panel. This includes login with password, passwordless login, 2FA and a password-reset. See [Kirby CMS login methods](https://getkirby.com/docs/guide/authentication/login-methods) and [Kirby CMS auth options](https://getkirby.com/docs/reference/system/options/auth).

Of course, the look & feel will be different between Kirby CMS panel pages and the custom registration page. But luckily customizing will be more flexible in future version of Kirby - hopefully. Check [Kirby CMS Panel login plugin](https://getkirby.com/docs/reference/plugins/extensions/panel-login).

Especially, with the [advanced permissions](https://getkirby.com/docs/guide/users/permissions#role-based-permissions-in-user-blueprints) this should be working.

**Comment by ianhobbs** [comment]
I'm looking for a 'timed' and 'paid' member solution for our large org. Are you heading in that direction?

**Comment by Manuel-Steinberg** [comment]
Hi @ianhobbs "timed" users are an interesting use case. But somehow my first thought would be to handle this on page level. So timed pages rather timed users, since the complexity "countdowns" for specific users for specific pages could be tremendous. On Page level this would be less complex, but more restrictive.

For paid members have a look at [Memberkit](https://github.com/kreativ-anders/kirby-memberkit)
